apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ces
spec:
  version: "v0.1.0"
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/cloudogu/kubectl-ces-plugin/releases/download/v0.1.0/kubectl-ces_linux_amd64.tar.gz
      sha256: ""
      bin: "kubectl-ces"
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/cloudogu/kubectl-ces-plugin/releases/download/v0.1.0/kubectl-ces_darwin_amd64.tar.gz
      sha256: ""
      bin: "kubectl-ces"
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/cloudogu/kubectl-ces-plugin/releases/download/v0.1.0/kubectl-ces_windows_amd64.zip
      sha256: ""
      bin: "kubectl-ces.exe"
  shortDescription: A new plugin
  homepage: https://github.com/cloudogu/kubectl-ces-plugin
  caveats: |
    * For resources that are not in default namespace, currently you must
      specify -n/--namespace explicitly (the current namespace setting is not
      yet used).
  description: |
    A `kubectl` plugin that simplifies interaction and maintenance of a multi-node Cloudogu EcoSystem.
